### ISSUE TITLE
Лотерея 2.0 / Орфографическая ошибка

### ISSUE THREAD

**Issue by Chierneejo** [AdvanceRoleplay/site-bugs#11]
http://adimg.ru/ZTZc.jpg

**Comment by Chierneejo** [comment]
![ztzc](https://user-images.githubusercontent.com/30554835/28746432-dac9b23e-7494-11e7-9978-a79c0d22ce72.jpg)

**Comment by advance-roleplay** [comment]
Исправлено. Зальем в скором времени.
