### ISSUE TITLE
Oтчеты. Лидерствo

### ISSUE THREAD

**Issue by orzik1998** [AdvanceRoleplay/site-bugs#2]
**_Приoритет: низкий_**
Суть проблемы: 
После того как игрока ставят на Лидерский пост организации, сразу же не увольняя, у него остается дни на ранге на котором он был до Лидерского поста. В ином случае после того как поставили, ему плюсуются  дни нахождения на ранге.
Предпoлoжительнo, баг не сайта, а игры
Пример:
![screenshot_1](https://cloud.githubusercontent.com/assets/4194301/21724640/523752ee-d446-11e6-8778-b6218c5a7832.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/4194301/21724641/523cb40a-d446-11e6-870e-bc6c72b66d26.png)

**Comment by AndreyRingo** [comment]
Действительно, если лидера назначала администрация либо президент с помощью команд /setleader, /newleader, то дни на ранге не обнулялись. Эта проблема была решена. Спасибо за сообщение о баге, приятной игры вам!
