### ISSUE TITLE
Бездомный гость в 901 доме / личный кабинет

### ISSUE THREAD

**Issue by Vadim-Yurievich** [AdvanceRoleplay/site-bugs#4]
Если человек проживает в гостях в доме № 901, то в личном кабинете в разделе "Проживание" он является бездомным, а не гостем 901 дома.

**Comment by orzik1998** [comment]
**- В игре пoказывается прoживание?
- Есть скриншoт/видеo пoдтверждающее ваши слoва?**

**Comment by xakdog** [comment]
@Vadim-Yurievich Проживание в гостях сейчас вообще не отображается на сайте, не важно 901 дом или какой-то другой. Добавим

**Comment by xakdog** [comment]
Fixed
